/**
 * SOURCE OF TRUTH — Catalogue des rôles et leurs permissions.
 *
 * Ce fichier est la SEULE définition des rôles.
 * Utilisé par :
 *  - seed.controller.ts (endpoint POST /api/v1/seed — dev/reset)
 *  - seed-users-sync.service.ts (démarrage automatique du serveur)
 *
 * Pour ajouter un rôle ou modifier ses permissions : modifier uniquement ce fichier.
 */

import { PERMISSION_CATALOG } from '../config/permissions.js';

export interface RoleDef {
  code:        string;
  name:        string;
  description: string;
  permissions: string[] | 'ALL';
}

export const ROLE_CATALOG: RoleDef[] = [
  {
    code:        'GESTIONNAIRE_SYSTEME',
    name:        'Gestionnaire Système',
    description: 'Accès complet à toutes les fonctionnalités du système, y compris la gestion des tenants. Réservé aux administrateurs de la plateforme.',
    permissions: 'ALL',
  },
  {
    code:        'DG',
    name:        'Direction Générale',
    description: 'Accès complet à toutes les fonctionnalités opérationnelles et stratégiques du projet.',
    permissions: 'ALL',
  },
  {
    code:        'SG',
    name:        'Secrétariat Général',
    description: 'Gère les flux administratifs et approuve les demandes : appels d\'offres, commandes, factures, avenants, réceptions et documents.',
    permissions: [
      'workflow:read', 'workflow:manage',
      'tender:read', 'tender:approve',
      'purchase-order:read', 'purchase-order:approve',
      'change-order:read', 'change-order:approve',
      'invoice:read', 'invoice:approve',
      'work-acceptance:read', 'work-acceptance:approve',
      'document:create', 'document:read', 'document:update',
      'meeting:create', 'meeting:read', 'meeting:update',
      'rfi:read',
      'project:read',
      'contract:read',
      'report:read',
      'audit-log:read',
    ],
  },
  {
    code:        'DIRECTEUR',
    name:        'Directeur',
    description: 'Décideur stratégique : supervise les budgets, valide les contrats, approuve les engagements majeurs et pilote via les tableaux de bord.',
    permissions: [
      'project:read', 'project:update', 'project:metadata:update', 'project:team:update', 'project:phase:transition', 'project:read:all',
      'project-lot:read',
      'wbs:read',
      'resource:read',
      'task:read', 'task:update',
      'tender:read', 'tender:approve',
      'purchase-order:read', 'purchase-order:approve',
      'supplier:read',
      'delivery:read',
      'contract:read', 'contract:update',
      'change-order:read', 'change-order:approve',
      'rfi:read',
      'submittal:read',
      'budget:create', 'budget:read', 'budget:update',
      'invoice:read', 'invoice:approve',
      'payment:read',
      'situation-travaux:read',
      'report:read', 'report:validate',
      'control-report:read', 'control-report:approve',
      'work-acceptance:read', 'work-acceptance:approve',
      'daily-log:read',
      'inspection:read',
      'incident:read',
      'punch-item:read',
      'meeting:read',
      'document:read',
      'workflow:read',
      'audit-log:read',
    ],
  },
  {
    code:        'CHEF_PROJET',
    name:        'Chef de Projet',
    description: 'Gère opérationnellement le projet : planning, tâches, budgets, rapports et coordination des équipes.',
    permissions: [
      'project:read', 'project:update', 'project:metadata:update', 'project:team:update', 'project:phase:transition', 'project:read:all',
      'project-lot:create', 'project-lot:read', 'project-lot:update',
      'wbs:create', 'wbs:read', 'wbs:update',
      'resource:read',
      'task:create', 'task:read', 'task:update', 'task:delete',
      'budget:read', 'budget:update',
      'situation-travaux:read',
      'invoice:read',
      'payment:read',
      'contract:read', 'contract:update',
      'change-order:create', 'change-order:read', 'change-order:update',
      'rfi:create', 'rfi:read', 'rfi:update',
      'submittal:read',
      'tender:read',
      'purchase-order:read',
      'supplier:read',
      'delivery:read',
      'report:create', 'report:read', 'report:update', 'report:validate',
      'control-report:read',
      'work-acceptance:read',
      'daily-log:read',
      'inspection:read',
      'incident:read',
      'punch-item:read',
      'execution-note:create', 'execution-note:read', 'execution-note:update',
      'document:create', 'document:read', 'document:update',
      'meeting:create', 'meeting:read', 'meeting:update',
      'workflow:read',
      'audit-log:read',
    ],
  },
  {
    code:        'CHEF_CHANTIER',
    name:        'Chef de Chantier',
    description: 'Pilote les opérations quotidiennes sur le terrain : planning, journal de chantier, incidents et inspections.',
    permissions: [
      'project:read',
      'project-lot:read',
      'wbs:read',
      'task:create', 'task:read', 'task:update',
      'resource:read',
      'daily-log:create', 'daily-log:read', 'daily-log:update', 'daily-log:delete',
      'inspection:create', 'inspection:read', 'inspection:update',
      'incident:create', 'incident:read', 'incident:update',
      'punch-item:create', 'punch-item:read', 'punch-item:update',
      'work-acceptance:create', 'work-acceptance:read',
      'report:create', 'report:read', 'report:update',
      'control-report:create', 'control-report:read', 'control-report:update',
      'document:create', 'document:read', 'document:update',
      'meeting:create', 'meeting:read', 'meeting:update',
      'rfi:create', 'rfi:read', 'rfi:update',
      'delivery:read',
      'goods-receipt:read',
      'stock:read',
    ],
  },
  {
    code:        'CONTROLEUR_CHANTIER',
    name:        'Contrôleur de Chantier',
    description: 'Vérifie la conformité des travaux, audite les réceptions, émet et approuve les rapports de contrôle.',
    permissions: [
      'project:read',
      'project-lot:read',
      'wbs:read',
      'task:read',
      'control-report:create', 'control-report:read', 'control-report:update', 'control-report:approve',
      'work-acceptance:create', 'work-acceptance:read', 'work-acceptance:update', 'work-acceptance:approve',
      'inspection:create', 'inspection:read', 'inspection:update', 'inspection:delete',
      'punch-item:create', 'punch-item:read', 'punch-item:update', 'punch-item:delete',
      'incident:read',
      'daily-log:read',
      'report:read', 'report:validate',
      'budget:read',
      'contract:read',
      'rfi:read',
      'document:read',
      'meeting:read',
    ],
  },
  {
    code:        'ACHETEUR',
    name:        'Acheteur',
    description: 'Gère les achats, fournisseurs, appels d\'offres, stocks et réceptions de marchandises.',
    permissions: [
      'supplier:create', 'supplier:read', 'supplier:update', 'supplier:delete',
      'tender:create', 'tender:read', 'tender:update',
      'purchase-order:create', 'purchase-order:read', 'purchase-order:update',
      'delivery:create', 'delivery:read', 'delivery:update',
      'goods-receipt:create', 'goods-receipt:read',
      'warehouse:read',
      'warehouse-location:read',
      'stock:read', 'stock:update',
      'inventory:read', 'inventory:update',
      'erp-sync:read',
      'contract:read',
      'document:read',
      'meeting:read',
    ],
  },
  {
    code:        'RESPONSABLE_APPELS_OFFRES',
    name:        'Responsable Appels d\'Offres',
    description: 'Gère exclusivement le cycle des appels d\'offres : préparation, consultation et suivi, sans accès aux achats, stocks ni validations hors périmètre.',
    permissions: [
      'tender:create', 'tender:read', 'tender:update',
      'supplier:read',
      'document:read',
      'meeting:read',
      'project:read',
      'project-lot:read',
    ],
  },
  {
    code:        'GESTIONNAIRE_RH',
    name:        'Gestionnaire RH / Ressources',
    description: 'Administre les ressources humaines et matérielles affectées aux projets.',
    permissions: [
      'resource:create', 'resource:read', 'resource:update', 'resource:delete',
      'user:create', 'user:read', 'user:update',
      'task:read',
      'project:read',
      'document:read',
    ],
  },
  {
    code:        'COMPTABLE',
    name:        'Comptable',
    description: 'Suit les engagements financiers : factures, paiements, budgets et situations de travaux.',
    permissions: [
      'budget:create', 'budget:read', 'budget:update',
      'situation-travaux:create', 'situation-travaux:read', 'situation-travaux:update',
      'invoice:create', 'invoice:read', 'invoice:update',
      'payment:create', 'payment:read',
      'contract:read',
      'change-order:read',
      'report:read',
      'document:read',
      'audit-log:read',
    ],
  },
  {
    code:        'CONSULTANT',
    name:        'Consultant (Lecture seule)',
    description: 'Accès en lecture seule pour les parties prenantes externes, maîtres d\'ouvrage et auditeurs.',
    permissions: [
      'project:read',
      'project-lot:read',
      'wbs:read',
      'task:read',
      'document:read',
      'meeting:read',
      'rfi:read',
      'report:read',
      'control-report:read',
      'work-acceptance:read',
      'inspection:read',
      'incident:read',
      'punch-item:read',
      'daily-log:read',
    ],
  },
];
