import { Router } from "express";
import authRouter from './auth.routes.js';
import projectRouter from './project.routes.js';
import resourceRouter from './resource.routes.js';
import procurementRouter from './procurement.routes.js';
import financeRouter from './finance.routes.js';
import contractRouter from './contract.routes.js';
import dailyLogRouter from './daily-log.routes.js';
import weeklyReportRouter from './weekly-report.routes.js';
import inspectionRouter from './inspection.routes.js';
import punchItemRouter from './punch-item.routes.js';
import incidentRouter from './incident.routes.js';
import workAcceptanceRouter from './work-acceptance.routes.js';
import seedRouter from './seed.routes.js';
import rbacRouter from './rbac.routes.js';
import tenantRouter from './tenant.routes.js';
import documentRouter from './document.routes.js';
import meetingRouter from './meeting.routes.js';
import rfiRouter from './rfi.routes.js';
import controlReportRouter from './control-report.routes.js';
import dashboardRouter from './dashboard.routes.js';
import validationRouter from './validation.routes.js';
import glpiRouter from './glpi.routes.js';
import photoRouter from './photo.routes.js';

const router = Router();

router.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

router.use("/auth", authRouter);
router.use("/projects", projectRouter);
router.use("/resources", resourceRouter);
router.use("/procurement", procurementRouter);
router.use("/finance", financeRouter);
router.use("/contracts", contractRouter);
router.use("/daily-logs", dailyLogRouter);
router.use("/weekly-reports", weeklyReportRouter);
router.use("/inspections", inspectionRouter);
router.use("/punch-items", punchItemRouter);
router.use("/incidents", incidentRouter);
router.use("/work-acceptances", workAcceptanceRouter);
router.use("/seed", seedRouter);
router.use("/rbac", rbacRouter);
router.use("/tenants", tenantRouter);
router.use('/documents', documentRouter);
router.use('/photos', photoRouter);
router.use('/meetings',  meetingRouter);
router.use('/rfis',      rfiRouter);
router.use('/control-reports', controlReportRouter);
router.use('/dashboard', dashboardRouter);
router.use('/validation', validationRouter);
router.use('/glpi', glpiRouter);
export default router;
