import { z } from 'zod';

const dateLike = z.union([z.string().min(1), z.date()]).nullable().optional();
const numberLike = z.union([z.number(), z.string().min(1)]).nullable().optional();

export const createControlReportSchema = z.object({
  project_id: numberLike,
  lot_id: numberLike,
  task_id: numberLike,
  reference: z.string().min(1).max(120).optional(),
  title: z.string().max(255).nullable().optional(),
  comment: z.string().min(1).max(20000),
  type: z.string().max(50).optional(),
  category: z.string().max(80).nullable().optional(),
  status: z.string().max(50).optional(),
  severity: z.string().max(50).optional(),
  priority: z.string().max(50).optional(),
  discipline: z.string().max(120).nullable().optional(),
  sub_discipline: z.string().max(120).nullable().optional(),
  location: z.string().max(255).nullable().optional(),
  zone_code: z.string().max(80).nullable().optional(),
  latitude: numberLike,
  longitude: numberLike,
  source_channel: z.string().max(40).nullable().optional(),
  inspection_method: z.string().max(80).nullable().optional(),
  observed_by_name: z.string().max(255).nullable().optional(),
  observed_by_company: z.string().max(255).nullable().optional(),
  report_date: dateLike,
  due_date: dateLike,
  target_response_at: dateLike,
  target_resolution_at: dateLike,
  first_response_at: dateLike,
  resolved_at: dateLike,
  closed_at: dateLike,
  root_cause: z.string().max(20000).nullable().optional(),
  corrective_action_summary: z.string().max(20000).nullable().optional(),
  preventive_action_summary: z.string().max(20000).nullable().optional(),
  closure_summary: z.string().max(20000).nullable().optional(),
  assigned_to_id: numberLike,
  sla_breached: z.boolean().optional(),
  escalation_level: numberLike,
  rejected_reason: z.string().max(5000).nullable().optional(),
}).passthrough().refine((payload) => payload.project_id !== undefined && payload.project_id !== null && payload.project_id !== '', {
  message: 'project_id is required',
});

export const updateControlReportSchema = z.object({
  project_id: numberLike,
  lot_id: numberLike,
  task_id: numberLike,
  reference: z.string().min(1).max(120).optional(),
  title: z.string().max(255).nullable().optional(),
  comment: z.string().min(1).max(20000).optional(),
  type: z.string().max(50).optional(),
  category: z.string().max(80).nullable().optional(),
  status: z.string().max(50).optional(),
  severity: z.string().max(50).optional(),
  priority: z.string().max(50).optional(),
  discipline: z.string().max(120).nullable().optional(),
  sub_discipline: z.string().max(120).nullable().optional(),
  location: z.string().max(255).nullable().optional(),
  zone_code: z.string().max(80).nullable().optional(),
  latitude: numberLike,
  longitude: numberLike,
  source_channel: z.string().max(40).nullable().optional(),
  inspection_method: z.string().max(80).nullable().optional(),
  observed_by_name: z.string().max(255).nullable().optional(),
  observed_by_company: z.string().max(255).nullable().optional(),
  report_date: dateLike,
  due_date: dateLike,
  target_response_at: dateLike,
  target_resolution_at: dateLike,
  first_response_at: dateLike,
  resolved_at: dateLike,
  closed_at: dateLike,
  root_cause: z.string().max(20000).nullable().optional(),
  corrective_action_summary: z.string().max(20000).nullable().optional(),
  preventive_action_summary: z.string().max(20000).nullable().optional(),
  closure_summary: z.string().max(20000).nullable().optional(),
  assigned_to_id: numberLike,
  sla_breached: z.boolean().optional(),
  escalation_level: numberLike,
  rejected_reason: z.string().max(5000).nullable().optional(),
  status_reason: z.string().max(5000).nullable().optional(),
  status_comment: z.string().max(20000).nullable().optional(),
}).passthrough();

export const rejectControlReportSchema = z.object({
  rejected_reason: z.string().min(3).max(5000),
}).passthrough();

export const createControlReportActionSchema = z.object({
  subject: z.string().min(1).max(255),
  description: z.string().max(10000).nullable().optional(),
  action_type: z.string().max(50).optional(),
  priority: z.string().max(50).optional(),
  responsible_id: numberLike,
  owner_name: z.string().max(255).nullable().optional(),
  due_date: dateLike,
  started_at: dateLike,
  status: z.string().max(50).optional(),
  completed_at: dateLike,
  escalation_level: numberLike,
  escalation_reason: z.string().max(5000).nullable().optional(),
  escalated_at: dateLike,
}).passthrough();

export const updateControlReportActionSchema = z.object({
  subject: z.string().min(1).max(255).optional(),
  description: z.string().max(10000).nullable().optional(),
  action_type: z.string().max(50).optional(),
  priority: z.string().max(50).optional(),
  responsible_id: numberLike,
  owner_name: z.string().max(255).nullable().optional(),
  due_date: dateLike,
  started_at: dateLike,
  status: z.string().max(50).optional(),
  completed_at: dateLike,
  verified_at: dateLike,
  verified_by: numberLike,
  verification_note: z.string().max(10000).nullable().optional(),
  completion_evidence_url: z.string().max(2000).nullable().optional(),
  sequence_no: numberLike,
  escalation_level: numberLike,
  escalation_reason: z.string().max(5000).nullable().optional(),
  escalated_at: dateLike,
}).passthrough();

export const createControlReportAttachmentSchema = z.object({
  url: z.string().min(1).max(2000),
  storage_key: z.string().max(500).nullable().optional(),
  file_name: z.string().max(500).nullable().optional(),
  file_type: z.string().max(120).nullable().optional(),
  mime_type: z.string().max(255).nullable().optional(),
  file_size_bytes: numberLike,
  checksum_sha256: z.string().max(255).nullable().optional(),
  source: z.string().max(40).optional(),
  caption: z.string().max(5000).nullable().optional(),
  taken_at: dateLike,
  latitude: numberLike,
  longitude: numberLike,
  is_primary_evidence: z.boolean().optional(),
  external_system: z.string().max(120).nullable().optional(),
  external_id: z.string().max(255).nullable().optional(),
  source_updated_at: dateLike,
}).passthrough();

export const updateControlReportAttachmentSchema = z.object({
  url: z.string().min(1).max(2000).optional(),
  storage_key: z.string().max(500).nullable().optional(),
  file_name: z.string().max(500).nullable().optional(),
  file_type: z.string().max(120).nullable().optional(),
  mime_type: z.string().max(255).nullable().optional(),
  file_size_bytes: numberLike,
  checksum_sha256: z.string().max(255).nullable().optional(),
  source: z.string().max(40).optional(),
  caption: z.string().max(5000).nullable().optional(),
  taken_at: dateLike,
  latitude: numberLike,
  longitude: numberLike,
  is_primary_evidence: z.boolean().optional(),
  external_system: z.string().max(120).nullable().optional(),
  external_id: z.string().max(255).nullable().optional(),
  source_updated_at: dateLike,
}).passthrough();
